# Base configuration for satellite detection and segmentation

project:
  name: "satellite-detection"
  version: "0.1.0"
  description: "Satellite detection using CNN models (U-Net, Faster R-CNN, YOLOv8)"

data:
  raw_path: "/home/tanman/datasets/playground/NAPA2_Audacity_v2_training/images/"
  groundtruth_file: "/home/tanman/datasets/playground/NAPA2_Audacity_v2_training/gt.json"
  real_test_path: "/home/tanman/datasets/playground/NAPA2_Audacity_v2_training/spacecloud/"
  processed_path: "data/processed/"
  splits_path: "data/splits/"
  
  # Data splits
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  
  # Cross validation
  cv_folds: 5
  
  # Advanced splitting options
  n_pose_clusters: 10  # Number of pose clusters for stratified splitting
  stratified_splitting: true  # Use pose-based stratified splitting
  pose_diversity_analysis: true  # Analyze and report pose diversity metrics
  
  # Image preprocessing
  image_size: [512, 512]
  normalize: true
  augmentation: true

training:
  batch_size: 16
  num_epochs: 100
  learning_rate: 0.001
  optimizer: "adamw"
  scheduler: "cosine"
  warmup_epochs: 5
  
  # Loss weights
  detection_loss_weight: 1.0
  bbox_regression_weight: 1.0
  objectness_weight: 1.0
  classification_weight: 1.0
  
  # Early stopping
  patience: 10
  min_delta: 0.001

evaluation:
  metrics:
    detection: ["mAP@0.5", "mAP@0.5:0.95", "precision", "recall", "F1"]
    bbox: ["IoU", "GIoU", "DIoU", "CIoU"]
  
  visualization: true
  save_predictions: true

model:
  type: "unet"  # Options: unet, fasterrcnn, yolov8
  
  # U-Net configuration (detection-focused)
  unet:
    n_channels: 3
    num_classes: 1  # satellite detection (no background)
    base_channels: 64
    depth: 4
    bilinear: true
    use_attention: false
    dropout_rate: 0.1
    use_auxiliary_outputs: false
    auxiliary_weight: 0.4
    
  # Faster R-CNN configuration  
  fasterrcnn:
    num_classes: 2  # background + satellite
    backbone_name: "resnet50"
    pretrained_backbone: true
    trainable_backbone_layers: 3
    min_size: 800
    max_size: 1333
    rpn_anchor_sizes: [32, 64, 128, 256, 512]
    rpn_aspect_ratios: [0.5, 1.0, 2.0]
    rpn_fg_iou_thresh: 0.7
    rpn_bg_iou_thresh: 0.3
    box_fg_iou_thresh: 0.5
    box_bg_iou_thresh: 0.5
    box_score_thresh: 0.05
    box_nms_thresh: 0.5
    box_detections_per_img: 100
    use_keypoints: false
    num_keypoints: 8
    use_multiscale: false
    scales: [600, 800, 1000, 1200]
    
  # YOLOv8 configuration (detection-only)
  yolov8:
    num_classes: 1  # satellite class (no background)
    input_channels: 3
    width_mult: 1.0  # Model scaling factors
    depth_mult: 1.0
    confidence_threshold: 0.25
    iou_threshold: 0.45
    max_detections: 300

mlflow:
  tracking_uri: "mlruns"
  experiment_name: "satellite-detection"
  
hardware:
  device: "cuda"
  num_workers: 4
  pin_memory: true
  mixed_precision: true
